
p1: 6

feign:
    hystrix:
        enabled: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true

ribbon:
    eureka:
        enabled: true
    serverListRefreshInterval: 3
    
    
#Development
#eureka.client.registryFetchIntervalSeconds=3
#ribbon.serverListRefreshInterval=3