
spring:
  profiles:
    active: "dev" 
 
feign:
    hystrix:
        enabled: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        
ribbon:
    eureka:
        enabled: true
    serverListRefreshInterval: 3
    
 kafka:
  bootstrap-servers: localhost:9092   
  topic:
      test: "test"
      

---
    
spring:
    profiles: dev


    
---
    
spring:
    profiles: prod
    
    