
spring:
  profiles:
    active: "dev" 
 
feign:
    hystrix:
        enabled: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        
ribbon:
    eureka:
        enabled: true
    serverListRefreshInterval: 3
    
kafka:
    bootstrap-servers: localhost:9092   
    topic:
        topic1: topic1
    group:
        group1: group1

---
    
spring:
    profiles: dev


    
---
    
spring:
    profiles: prod
    
    