
spring:
  profiles:
    active: "dev"


feign:
    hystrix:
        enabled: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true

ribbon:
    eureka:
        enabled: true
    serverListRefreshInterval: 3
    
    
---
    
spring:
    profiles: dev

p1: 6    
    
---
    
spring:
    profiles: prod
    
p1: 7
    
#Development
#eureka.client.registryFetchIntervalSeconds=3
#ribbon.serverListRefreshInterval=3