 
feign:
    hystrix:
        enabled: true
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        
ribbon:
    eureka:
        enabled: true
    serverListRefreshInterval: 3